package com.tomppi.enderslicer.printer

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.rules.TemporaryFolder

/** Reading a g-code file's own header, which is what makes a file list useful. */
class KlipperGcodeFilesTest {
    @get:Rule
    val folder = TemporaryFolder()

    private fun gcode(name: String, header: String) =
        folder.newFile(name).apply { writeText(header + "\nG1 X0 Y0\n") }

    @Test
    fun anOrcaSlicerHeaderIsReadWhole() {
        val file = gcode(
            "cube.gcode",
            listOf(
                "; generated by OrcaSlicer 2.2.0 on 2026-09-20 at 12:00:00",
                "; estimated printing time (normal mode) = 1h 23m 45s",
                "; filament used [mm] = 1234.56",
                "; filament used [g] = 36.78",
                "; layer_height = 0.2",
                "; total_layer_number = 123",
            ).joinToString("\n"),
        )
        val parsed = KlipperGcodeFiles.read(file)
        assertEquals("OrcaSlicer 2.2.0", parsed.slicer)
        assertEquals(1 * 3600 + 23 * 60 + 45, parsed.estimatedSeconds)
        assertEquals(1234.56, parsed.filamentMillimetres!!, 0.001)
        assertEquals(36.78, parsed.filamentGrams!!, 0.001)
        assertEquals(0.2, parsed.layerHeight!!, 0.001)
        assertEquals(123, parsed.layerCount)
    }

    @Test
    fun aCuraHeaderIsReadToo() {
        val file = gcode(
            "cura.gcode",
            listOf(
                ";FLAVOR:Marlin",
                ";Generated with Cura_SteamEngine 5.6.0",
                ";TIME:3723",
                ";Filament used: 2.5m",
                ";Layer height: 0.16",
                ";LAYER_COUNT:88",
            ).joinToString("\n"),
        )
        val parsed = KlipperGcodeFiles.read(file)
        assertEquals("Cura_SteamEngine 5.6.0", parsed.slicer)
        assertEquals(3723, parsed.estimatedSeconds)
        assertEquals(0.16, parsed.layerHeight!!, 0.001)
        assertEquals(88, parsed.layerCount)
    }

    @Test
    fun aPrusaSlicerHeaderIsReadFromItsFlavorAlone() {
        val file = gcode("prusa.gcode", "; generated by PrusaSlicer 2.8.0 on 2026-01-01\n; layer_height = 0.25")
        val parsed = KlipperGcodeFiles.read(file)
        assertEquals("PrusaSlicer 2.8.0", parsed.slicer)
        assertEquals(0.25, parsed.layerHeight!!, 0.001)
    }

    @Test
    fun theDurationsSlicersWriteAreAllUnderstood() {
        assertEquals(45, KlipperGcodeFiles.parseDuration("45s"))
        assertEquals(23 * 60, KlipperGcodeFiles.parseDuration("23m"))
        assertEquals(2 * 3600 + 30 * 60, KlipperGcodeFiles.parseDuration("2h 30m"))
        assertEquals(3600 + 23 * 60 + 45, KlipperGcodeFiles.parseDuration("1h 23m 45s"))
        assertNull(KlipperGcodeFiles.parseDuration("the printer's own guess"))
    }

    @Test
    fun theThumbnailIsTakenFromBetweenItsMarkers() {
        val image = listOf("iVBORw0KGgoAAAANSUhEUg", "AAAAADUlEQVR42mNk")
        val file = gcode(
            "thumb.gcode",
            listOf(
                "; thumbnail begin 16x16 128",
                "; " + image[0],
                "; " + image[1],
                "; thumbnail end",
                "; something after it",
            ).joinToString("\n"),
        )
        val parsed = KlipperGcodeFiles.read(file)
        // The comment markers and the line breaks are not part of the image.
        assertEquals(image.joinToString(""), parsed.thumbnail)
    }

    @Test
    fun aFileWithNoThumbnailHasNone() {
        val file = gcode("no-thumb.gcode", "; generated by OrcaSlicer 2.2.0")
        assertNull(KlipperGcodeFiles.read(file).thumbnail)
    }

    @Test
    fun filesThatAreNotGcodeAreNotListed() {
        folder.newFile("notes.txt")
        folder.newFile("model.stl")
        gcode("print.gcode", "; layer_height = 0.2")
        val listed = KlipperGcodeFiles.list(folder.root)
        assertEquals(listOf("print.gcode"), listed.map { it.name })
    }

    @Test
    fun theNewestFileComesFirst() {
        val older = gcode("older.gcode", "; layer_height = 0.2")
        val newer = gcode("newer.gcode", "; layer_height = 0.2")
        older.setLastModified(1_000_000L)
        newer.setLastModified(2_000_000L)
        assertEquals(listOf("newer.gcode", "older.gcode"), KlipperGcodeFiles.list(folder.root).map { it.name })
    }

    @Test
    fun aFileWithNoHeaderIsStillAFile() {
        val plain = folder.newFile("plain.gcode").apply { writeText("G28\nG1 X10\n") }
        val parsed = KlipperGcodeFiles.read(plain)
        assertEquals("plain.gcode", parsed.name)
        assertEquals("", parsed.slicer)
        assertNull(parsed.estimatedSeconds)
        assertTrue(parsed.sizeBytes > 0)
    }
}
