package com.tomppi.enderslicer.model

import com.tomppi.enderslicer.engine.PrusaConfigWriter
import com.tomppi.enderslicer.engine.PrusaPresetValues
import java.io.File
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test

/**
 * Fidelity of the PrusaSlicer preset resolver against the shipped snapshot.
 *
 * prusa3-base.json is a configuration the real PrusaSlicer 3.0 saved for an MK4 with a 0.4
 * nozzle: 222 print, 65 printer and 68 filament values. Resolving that same machine out of the
 * bundled repository has to reproduce it - not approximately, value for value - because that
 * snapshot is what the app slices with today. Every value the resolver states for a key the
 * snapshot carries is compared here, so a resolver that silently stopped applying a branch, or
 * applied the wrong one, fails the test instead of slicing with the wrong profile.
 *
 * Skips itself when the repository JSON is absent (it is generated by the fetch script).
 */
class PrusaPresetCatalogSnapshotTest {

    private val assets = File("src/main/assets")
    private val presetJson = File(assets, "prusa-presets.json")
    private val repository by lazy { PrusaPresetRepository.parse(presetJson.readText()) }
    private val catalog by lazy { PrusaPresetCatalog(repository) }
    private val baseConfig by lazy { File(assets, "prusa3-base.json").readText() }

    @Test
    fun `every machine the bundle configures is offered`() {
        assumeTrue(presetJson.isFile)
        val printers = catalog.printers()
        assertEquals(32, printers.size)

        val mk4 = catalog.printer("mk4")!!
        assertEquals("Prusa MK4 0.4", mk4.label)
        assertEquals("MK4", mk4.baseModel)
        assertEquals("MK4", mk4.model)

        val coreOne = catalog.printer("c1")!!
        assertEquals("Prusa CORE One 0.4", coreOne.label)

        val xl = catalog.printer("xl-2t")!!
        assertEquals(2, xl.toolCount)
    }

    @Test
    fun `every condition in the bundle parses`() {
        assumeTrue(presetJson.isFile)
        val conditions = mutableSetOf<String>()
        for (document in repository.documents) {
            document.condition?.let(conditions::add)
            collect(document.variants, conditions)
        }
        assertEquals(138, conditions.size)
        for (condition in conditions) {
            PrusaPresetCondition.parse(condition)
        }
    }

    @Test
    fun `resolving the MK4 printer preset reproduces the shipped snapshot`() {
        assumeTrue(presetJson.isFile)
        val printer = catalog.printer("mk4")!!
        val print = catalog.defaultPrint(printer)
        val filament = catalog.defaultFilament(printer)
        assertEquals("0.20mm SPEED @MK4 0.4", print)
        assertEquals("Prusament PLA", filament)

        val buckets = PrusaPresetValues.map(
            baseConfigJson = baseConfig,
            printerValues = catalog.resolvePrinter(printer),
            printValues = catalog.resolvePrint(printer, print!!),
            // The snapshot was saved with the generic material; the bundle's own default for this
            // machine is Prusament PLA, which is what the picker preselects.
            filamentValues = catalog.resolveFilament(printer, "Generic PLA"),
        )
        assertMatchesSnapshot("printer_settings", buckets.printer, 24)
        assertMatchesSnapshot("print_settings", buckets.print, 95)
        assertMatchesSnapshot("filament_settings", buckets.filament, 39)
    }

    /**
     * The configuration the app would hand the console for a preset selection, written out so the
     * engine probe (scripts/... /probe-prusa-config.sh) can slice with it on a device. The
     * assertions beside it keep the app's own values on top of the presets.
     */
    @Test
    fun `the written configuration keeps the app on top of the presets`() {
        assumeTrue(presetJson.isFile)
        val printer = catalog.printer("mk4")!!
        val buckets = PrusaPresetValues.map(
            baseConfigJson = baseConfig,
            printerValues = catalog.resolvePrinter(printer),
            printValues = catalog.resolvePrint(printer, catalog.defaultPrint(printer)!!),
            filamentValues = catalog.resolveFilament(printer, "Prusament PLA"),
        )
        val rendered = PrusaConfigWriter.render(
            settings = PrusaSliceSettings(layerHeightMm = 0.28, fillDensityPercent = 25.0),
            printer = PrinterDefinition(
                name = "Modified Ender 3 V2",
                widthMm = 230.0, depthMm = 230.0, heightMm = 250.0,
                buildPlateShape = "rectangular", originAtCenter = false,
                heatedBed = true, heatedBuildVolume = false,
                gcodeFlavor = "Marlin", extruders = 1,
                nozzleSizeMm = 0.4, filamentDiameterMm = 1.75,
                printheadXMinMm = -26.0, printheadYMinMm = -32.0,
                printheadXMaxMm = 32.0, printheadYMaxMm = 34.0,
                gantryHeightMm = 25.0,
            ),
            startGcode = "; app start",
            endGcode = "; app end",
            baseConfigJson = baseConfig,
            presets = buckets,
        )
        val configuration = JSONObject(rendered).getJSONObject("configuration")
        // The app's own settings win over the preset's, which is the whole point of the layering.
        assertEquals(0.28, configuration.getJSONObject("print_settings").getDouble("layer_height"), 1e-9)
        assertEquals("; app start", configuration.getJSONObject("printer_settings").getString("start_gcode"))
        // Values the app does not state come from the preset chain.
        assertEquals(
            "Prusa Polymers",
            configuration.getJSONObject("filament_settings").getJSONArray("filament_vendor").getString(0),
        )
        assertTrue(configuration.getJSONObject("printer_settings").length() > 40)

        val probe = File("build/prusa-preset-config.json")
        probe.parentFile?.mkdirs()
        probe.writeText(rendered)
    }

    @Test
    fun `quality profiles and materials follow the chosen machine`() {
        assumeTrue(presetJson.isFile)
        val mk4 = catalog.printer("mk4")!!
        val mini = catalog.printer("mini")!!
        val mk4Prints = catalog.prints(mk4)
        assertTrue(mk4Prints.contains("0.20mm SPEED @MK4 0.4"))
        assertTrue(mk4Prints.none { it.contains("MINI") })
        assertTrue(catalog.prints(mini).none { it.contains("MK4") })
        assertTrue(catalog.filaments(mk4).contains("Prusament PLA"))
    }

    @Test
    fun `first-match drops the quality profiles the hardware does not have`() {
        assumeTrue(presetJson.isFile)
        // A high-flow MK4S must not be offered the non-HF profiles that sit in a later sibling
        // branch of the same tree; the printer has one family per layer height.
        val mk4sPrints = catalog.prints(catalog.printer("mk4s")!!)
        assertEquals(8, mk4sPrints.size)
        assertTrue(mk4sPrints.all { it.endsWith("0.4HF") })
        assertTrue(mk4sPrints.contains("0.20mm SPEED @MK4S 0.4HF"))
        // Every tree is still fully listed where it is not competing with a matching sibling.
        assertEquals(5, catalog.prints(catalog.printer("mk4")!!).size)
        assertEquals(3, catalog.prints(catalog.printer("xl-1t")!!).size)
        assertEquals(4, catalog.prints(catalog.printer("c1indx-4t")!!).size)
    }

    @Test
    fun `every machine resolves a default quality profile and material`() {
        assumeTrue(presetJson.isFile)
        val missing = mutableListOf<String>()
        for (printer in catalog.printers()) {
            val print = catalog.defaultPrint(printer)
            if (print == null || catalog.resolvePrint(printer, print).isEmpty()) {
                missing.add(printer.id + " print")
            }
            val filament = catalog.defaultFilament(printer)
            if (filament == null || catalog.resolveFilament(printer, filament).isEmpty()) {
                missing.add(printer.id + " filament")
            }
        }
        assertEquals(emptyList<String>(), missing)
        // The machines whose profile is only a layer height or whose pointer does not match a
        // profile name: XL, XL+ and MINI / MK3.5.
        assertEquals("0.20mm", catalog.defaultPrint(catalog.printer("xl-1t")!!))
        assertEquals("0.10mm FAST DETAIL @MINI 0.4", catalog.defaultPrint(catalog.printer("mini")!!))
        assertEquals("Prusament PLA", catalog.defaultFilament(catalog.printer("mk3.5")!!))
    }

    @Test
    fun `a tool-print machine changes the settings with the quality profile`() {
        assumeTrue(presetJson.isFile)
        for (id in listOf("xl-1t", "xl+1t", "c1indx-4t")) {
            val printer = catalog.printer(id)!!
            val profiles = catalog.prints(printer)
            assertTrue(id + " offers no quality choice", profiles.size > 1)
            val first = catalog.resolvePrint(printer, profiles.first())
            val changed = profiles.drop(1).flatMap { name ->
                val other = catalog.resolvePrint(printer, name)
                (first.keys + other.keys).filter { first[it] != other[it] }
            }.distinct().filter { it !in AllSettingsCatalogs.PRUSA_MANAGED_KEYS }
            assertTrue(id + " quality profiles resolve identically", changed.isNotEmpty())
        }
        // The default profile applies the tool print the inherited pointer names.
        val xl = catalog.printer("xl-1t")!!
        assertEquals("0.20mm", catalog.defaultPrint(xl))
        assertEquals(0.2, catalog.resolvePrint(xl, "0.20mm")["raft_contact_distance"])
        assertEquals(0.15, catalog.resolvePrint(xl, "0.10mm")["raft_contact_distance"])
    }

    @Test
    fun `the catalogue reports whether it can serve a stored selection`() {
        assumeTrue(presetJson.isFile)
        assertNull(catalog.unavailableReason)
        assertNull(catalog.printer("no-such-machine"))
        val mk4 = catalog.printer("mk4")!!
        assertTrue(catalog.hasPrint(mk4, catalog.defaultPrint(mk4)!!))
        assertTrue(catalog.hasFilament(mk4, catalog.defaultFilament(mk4)!!))
    }

    private fun assertMatchesSnapshot(bucket: String, mapped: JSONObject, expected: Int) {
        val known = JSONObject(baseConfig).getJSONObject("configuration").getJSONObject(bucket)
        var compared = 0
        val mismatches = mutableListOf<String>()
        val keys = mapped.keys()
        while (keys.hasNext()) {
            val key = keys.next()
            if (!known.has(key)) continue
            compared++
            if (normalize(mapped.opt(key)) != normalize(known.opt(key))) {
                mismatches.add(key + ": resolved " + mapped.opt(key) + ", snapshot " + known.opt(key))
            }
        }
        assertEquals("values differing from the snapshot in " + bucket, emptyList<String>(), mismatches)
        // Pinned, not a lower bound: the repository is fetched from a pinned tag, so a change in
        // how much of it reaches the configuration has to show up here.
        assertEquals("keys of " + bucket + " covered by the snapshot", expected, compared)
        assertEquals("resolved keys in " + bucket, expected, mapped.length())
    }

    private fun collect(variants: List<PrusaPresetRepository.Variant>, into: MutableSet<String>) {
        for (variant in variants) {
            variant.condition?.let(into::add)
            collect(variant.variants, into)
        }
    }

    /** One canonical form, so 15, 15.0 and "15" compare equal, as do true and 1. */
    private fun normalize(value: Any?): String = when (value) {
        null -> "null"
        is JSONArray -> (0 until value.length()).joinToString(",", "[", "]") { normalize(value.opt(it)) }
        is JSONObject -> if (value.has("is_percent")) {
            "percent(" + number(value.opt("value")) + "," + value.optBoolean("is_percent") + ")"
        } else {
            value.keys().asSequence().toList().sorted()
                .joinToString(",", "{", "}") { it + "=" + normalize(value.opt(it)) }
        }
        is Boolean -> if (value) "1" else "0"
        is Number -> number(value)
        else -> value.toString()
    }

    private fun number(value: Any?): String {
        val double = (value as? Number)?.toDouble() ?: return value.toString()
        return if (double == double.toLong().toDouble()) double.toLong().toString() else double.toString()
    }
}
