package com.tomppi.enderslicer.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * The OrcaSlicer dialect, spelled the way the engine actually writes it.
 *
 * Both artifacts measured on the device use the PrusaSlicer envelope - `;LAYER_CHANGE` and
 * `; Z:` - which is what the engine writes for a non-Bambu vendor. The Bambu envelope's
 * `; CHANGE_LAYER` and `; Z_HEIGHT:` come from the machine profile's own layer_change_gcode
 * (GCode.cpp:4619-4622 picks by vendor), so this dialect accepts both. OrcaSlicer is a
 * PrusaSlicer fork, so the estimated-time and filament comments are the same text the Prusa
 * dialect already read.
 */
class GcodeOrcaDialectTest {

    private fun temporaryGcode(text: String): File {
        val file = File.createTempFile("orca-dialect", ".gcode")
        file.deleteOnExit()
        file.writeText(text.trimIndent() + "\n")
        return file
    }

    private val orcaBody = """
        ; generated by OrcaSlicer 2.4.2 on 2026-09-19 at 10:50:38
        ; estimated printing time (normal mode) = 27m 12s
        M104 S150
        G28
        G90
        M83
        ; CHANGE_LAYER
        ; Z_HEIGHT: 0.2
        ; LAYER_HEIGHT: 0.2
        ;BEFORE_LAYER_CHANGE
        ;0.2
        G92 E0
        G1 X108.979 Y95.158 E1.02121
        G1 X94.521 Y108.979 E1.06823
        ; CHANGE_LAYER
        ; Z_HEIGHT: 0.4
        ; LAYER_HEIGHT: 0.2
        ;BEFORE_LAYER_CHANGE
        ;0.4
        G92 E0
        G1 X100.0 Y100.0 E1.5
        ; filament used [mm] = 1374.01
    """

    @Test
    fun parsesOrcaLayerMarkersIntoNumberedLayers() {
        val file = temporaryGcode(orcaBody)

        val preview = GcodeLayerPreviewParser.parse(file, GcodeDialect.ORCA)

        assertEquals(2, preview.layers.size)
        assertEquals(1, preview.layers[0].number)
        assertEquals(0.2f, preview.layers[0].z, 0.001f)
        assertEquals(2, preview.layers[1].number)
        assertEquals(0.4f, preview.layers[1].z, 0.001f)
        assertTrue(preview.layers[0].sourceSegmentCount >= 2)
    }

    @Test
    fun bothLayerSpellingsTheEngineUsesAreRead() {
        // OrcaSlicer picks the envelope by vendor (GCode.cpp:4619-4622): a Bambu Lab printer gets
        // "; CHANGE_LAYER" and "; Z_HEIGHT:", every other vendor ";LAYER_CHANGE" and ";Z:" -
        // which is what both artifacts measured on the device use. The Bambu spelling is accepted
        // so a Bambu-vendor profile reads the same way.
        val prusaSpelling = temporaryGcode(
            """
            G90
            M83
            ;LAYER_CHANGE
            ;Z:0.2
            ;HEIGHT:0.2
            G1 X10 Y10 E0.5
            """,
        )
        val bambuSpelling = temporaryGcode(
            """
            G90
            M83
            ; CHANGE_LAYER
            ; Z_HEIGHT: 0.2
            ; LAYER_HEIGHT: 0.2
            G1 X10 Y10 E0.5
            """,
        )

        val fromPrusaSpelling = GcodeLayerPreviewParser.parse(prusaSpelling, GcodeDialect.ORCA)
        val fromBambuSpelling = GcodeLayerPreviewParser.parse(bambuSpelling, GcodeDialect.ORCA)

        assertEquals(1, fromPrusaSpelling.layers.size)
        assertEquals(0.2f, fromPrusaSpelling.layers[0].z, 0.001f)
        assertEquals(1, fromBambuSpelling.layers.size)
        assertEquals(0.2f, fromBambuSpelling.layers[0].z, 0.001f)
    }

    @Test
    fun theCuraLayerMarkerIsNotAnOrcaLayerMarker() {
        val file = temporaryGcode(
            """
            G90
            M83
            ;LAYER:1
            ;Z:0.2
            G1 X10 Y10 E0.5
            """,
        )

        val failure = runCatching { GcodeLayerPreviewParser.parse(file, GcodeDialect.ORCA) }
            .exceptionOrNull()

        assertTrue(
            "expected the Cura-only snippet to yield no layers, got " + failure,
            failure is IllegalArgumentException,
        )
    }

    @Test
    fun theCrealitySpaghettiDetectorCommandSurvivesTheSafetyGate() {
        // A device slice was refused with "rejects unmodeled persistent or machine-control
        // command M981", which is the Creality start G-code this app imports talking:
        // "M981 S1 P20000 ;open spaghetti detector". It is a runtime toggle the machine owns,
        // so the policy allows it with bounded arguments instead of refusing the whole slice.
        val file = temporaryGcode(
            """
            ; Ender 3 Custom Start G-code
            G92 E0 ; Reset Extruder
            G28 ; Home all axes
            M981 S1 P20000 ; open spaghetti detector
            G1 Z2.0 F3000 ; Move Z Axis up
            ; CHANGE_LAYER
            ; Z_HEIGHT: 0.2
            ; LAYER_HEIGHT: 0.2
            G1 X10 Y10 E1.0
            ; filament used [mm] = 12.0
            """,
        )

        val summary = GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "orca-ini",
            dialect = GcodeDialect.ORCA,
        )

        assertEquals(1, summary.layerCount)
        assertTrue(file.readText().contains("M981 S1 P20000"))
    }

    @Test
    fun anOutOfRangeSpaghettiDetectorArgumentIsStillRefused() {
        val file = temporaryGcode(
            """
            G28
            M981 S7 P20000 ; a detector mode that does not exist
            ; CHANGE_LAYER
            ; Z_HEIGHT: 0.2
            G1 X10 Y10 E1.0
            """,
        )

        val failure = runCatching {
            GcodeSanitizer.validateAndRepair(
                file = file,
                settingsTransport = "orca-ini",
                dialect = GcodeDialect.ORCA,
            )
        }.exceptionOrNull()

        assertTrue("expected the out-of-range mode to be refused, got " + failure, failure != null)
    }

    @Test
    fun countsOrcaLayersAndKeepsEstimateAndFilament() {
        val file = temporaryGcode(orcaBody)

        val summary = GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "orca-ini",
            dialect = GcodeDialect.ORCA,
        )

        assertEquals(2, summary.layerCount)
        assertEquals(1632, summary.estimatedSeconds)
        assertEquals(1374.01, summary.totalFilamentMillimeters, 0.001)
        val output = file.readText()
        assertTrue(output.contains("; estimated printing time (normal mode) = 27m 12s"))
        assertTrue(output.contains("; filament used [mm] = 1374.01"))
        assertTrue(output.contains(";ENDERSLICER_SETTINGS_TRANSPORT:orca-ini"))
    }

    @Test
    fun dropsVendorMachineLimitsFromAnOrcaSlice() {
        // The Orca vendor profiles carry M201-M205 machine limits (M201 X500 Y500 Z500 E5000,
        // Z acceleration 500 where the Prusa path pins 100); the target printer firmware
        // applies its own defaults, so the Prusa dialect's strip covers Orca too.
        val file = temporaryGcode(
            """
            ; generated by OrcaSlicer 2.4.2
            M201 X500 Y500 Z500 E5000
            M203 X500 Y500 Z20 E50
            M204 P500 R500 T500
            M205 X8 Y8 Z0.4 E2.5
            G28
            ;LAYER_CHANGE
            ; Z:0.2
            G1 X10 Y10 E1.0
            ; filament used [mm] = 12.0
            """,
        )

        GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "orca-ini",
            dialect = GcodeDialect.ORCA,
        )

        val output = file.readText()
        assertFalse(output.contains("M201 "))
        assertFalse(output.contains("M203 "))
        assertFalse(output.contains("M204 "))
        assertFalse(output.contains("M205 "))
        assertTrue(output.contains("G1 X10 Y10 E1.0"))
    }

    /**
     * The strip drops the machine limits a vendor profile carries, not the ones
     * the user wrote into their own start G-code: setting M201-M205 there is a
     * deliberate choice, and it used to be deleted from the published file.
     */
    @Test
    fun keepsTheMachineLimitsTheUserWroteInTheirOwnGcode() {
        val file = temporaryGcode(
            """
            ; generated by OrcaSlicer 2.4.2
            M201 X500 Y500 Z500 E5000
            M201 X900 Y900 Z100 E1000
            G28
            ;LAYER_CHANGE
            ; Z:0.2
            G1 X10 Y10 E1.0
            ; filament used [mm] = 12.0
            """,
        )

        GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "orca-ini",
            dialect = GcodeDialect.ORCA,
            userGcode = listOf("; custom start\nM201 X900 Y900 Z100 E1000\nG28"),
        )

        val output = file.readText()
        assertFalse("the vendor profile's limit is dropped", output.contains("M201 X500"))
        assertTrue("the user's own limit is kept", output.contains("M201 X900 Y900 Z100 E1000"))
    }

    @Test
    fun readsTheBambuFeatureTags() {
        // A Bambu-vendor profile tags roles with "; FEATURE:" where PrusaSlicer writes
        // ";TYPE:", so a preview that knew only the latter came out featureless.
        val file = temporaryGcode(
            """
            G90
            M83
            ; CHANGE_LAYER
            ; Z_HEIGHT: 0.2
            ; LAYER_HEIGHT: 0.2
            ; FEATURE: Support
            G1 X10 Y10 E0.5
            ; FEATURE: Inner wall
            G1 X12 Y10 E0.6
            ; FEATURE: Custom
            G1 X0 Y0
            """,
        )

        val preview = GcodeLayerPreviewParser.parse(file, GcodeDialect.ORCA)

        assertEquals(1, preview.layers.size)
        assertEquals(1, preview.layers[0].supportSegmentCount)
        assertEquals(2, preview.totalSegmentCount)
    }

    @Test
    fun readsBambuSpellingIntoTheNozzlePath() {
        // The nozzle-path view is shown for Orca slices too: a Bambu-vendor file opens with
        // "; CHANGE_LAYER" and states bead width and layer height as "; LINE_WIDTH:" and
        // "; LAYER_HEIGHT:".
        val file = temporaryGcode(
            """
            G90
            M83
            ; CHANGE_LAYER
            ; Z_HEIGHT: 0.2
            ; LAYER_HEIGHT: 0.25
            ; LINE_WIDTH: 0.6
            G1 X10 Y10 E0.5
            G1 X12 Y10 E0.6
            ; FEATURE: Custom
            G1 X0 Y0
            """,
        )

        val path = PrusaNozzlePathParser.parse(file, 100)

        assertEquals(2, path.moveCount)
        assertEquals(0.6f, path.moves[PrusaNozzlePath.WIDTH], 0.001f)
        assertEquals(0.25f, path.moves[PrusaNozzlePath.HEIGHT], 0.001f)
    }
}
