package com.tomppi.enderslicer.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/** PrusaSlicer gcode carries no Cura-style ;LAYER_COUNT:/;LAYER:/;TIME:/;Filament used: markers. */
class GcodeSanitizerPrusaDialectTest {
    @Test
    fun countsPrusaLayerChangeMarkersAndKeepsEstimateAndFilament() {
        val file = temporaryGcode(
            """
            ; generated by PrusaSlicer 2.9.6
            ;TYPE:Custom
            M104 S150
            G28
            ;LAYER_CHANGE
            ;Z:0.2
            ;HEIGHT:0.2
            G1 Z.2 F9000
            G1 X88.299 Y97.315
            G1 E2 F2400
            ;TYPE:Skirt/Brim
            ;LAYER_CHANGE
            ;Z:0.4
            G1 X90 Y96.821 E2.05259
            ;LAYER_CHANGE
            ;Z:0.6
            G1 X91 Y96.821 E2.15
            ;TYPE:Custom
            G1 Z29.48 F600
            M140 S0
            M104 S0
            ; filament used [mm] = 2273.04
            ; estimated printing time (normal mode) = 1h 23m 37s
            """.trimIndent(),
        )

        val summary = GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "prusa-ini",
            dialect = GcodeDialect.PRUSA,
        )

        assertEquals(3, summary.layerCount)
        assertEquals(5017, summary.estimatedSeconds)
        assertEquals(2273.04, summary.totalFilamentMillimeters, 0.001)
        assertEquals(2273.04, summary.filamentMillimeters, 0.001)
        val output = file.readText()
        assertTrue(output.contains("; estimated printing time (normal mode) = 1h 23m 37s"))
        assertTrue(output.contains("; filament used [mm] = 2273.04"))
        assertTrue(output.contains(";ENDERSLICER_SETTINGS_TRANSPORT:prusa-ini"))
    }

    @Test
    fun rejectsG28InsidePrusaLayers() {
        val file = temporaryGcode(
            """
            ;TYPE:Custom
            G28
            ;LAYER_CHANGE
            ;Z:0.2
            G1 Z.2 F9000
            G1 E2 F2400
            G28
            ;LAYER_CHANGE
            ;Z:0.4
            G1 X1 Y1
            ;LAYER_CHANGE
            ;Z:0.6
            G1 X2 Y2
            """.trimIndent(),
        )

        val error = runCatching {
            GcodeSanitizer.validateAndRepair(file, dialect = GcodeDialect.PRUSA)
        }.exceptionOrNull()
        assertTrue(error is GcodeSanitizer.UnsafeGcodeException || error is IllegalArgumentException)
        assertTrue(error?.message.orEmpty().contains("Unsafe G28"))
    }

    @Test
    fun allowsG28InPrusaEndGcodeAfterFinalLayer() {
        val file = temporaryGcode(
            """
            ;TYPE:Custom
            G28
            ;LAYER_CHANGE
            ;Z:0.2
            G1 Z.2 F9000
            G1 X10 Y10
            ;LAYER_CHANGE
            ;Z:0.4
            G1 X11 Y11
            ;LAYER_CHANGE
            ;Z:0.6
            G1 X12 Y12
            ;TYPE:Custom
            G28
            """.trimIndent(),
        )

        val summary = GcodeSanitizer.validateAndRepair(file, dialect = GcodeDialect.PRUSA)
        assertEquals(3, summary.layerCount)
    }

    @Test
    fun anAbsurdEstimatedTimeCommentDoesNotFailTheSlice() {
        // PrusaSlicer has already succeeded by the time this comment is read, so
        // a digit run longer than Int can hold must be clamped rather than thrown
        // as a NumberFormatException that the callers do not document.
        val file = temporaryGcode(
            """
            ; generated by PrusaSlicer 2.9.6
            ;TYPE:Custom
            G28
            ;LAYER_CHANGE
            ;Z:0.2
            G1 Z.2 F9000
            G1 X10 Y10
            G1 E2 F2400
            ; filament used [mm] = 12.5
            ; estimated printing time (normal mode) = 99999999999h
            """.trimIndent(),
        )

        val summary = GcodeSanitizer.validateAndRepair(
            file = file,
            settingsTransport = "prusa-ini",
            dialect = GcodeDialect.PRUSA,
        )

        val estimated = summary.estimatedSeconds
        assertTrue("expected a clamped estimate, got " + estimated, estimated != null && estimated > 0)
    }

    @Test
    fun clockFieldsAreClampedRatherThanLeftToOverflow() {
        assertEquals(0L, GcodeSanitizer.clockComponent(""))
        assertEquals(37L, GcodeSanitizer.clockComponent("37"))
        assertEquals(100_000L, GcodeSanitizer.clockComponent("99999999999999999999999"))
    }

    private fun temporaryGcode(content: String): File {
        val directory = kotlin.io.path.createTempDirectory("enderslicer-prusa-test").toFile()
        return File(directory, "output.gcode").apply { writeText(content) }
    }
}
