package com.tomppi.enderslicer.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class GcodeLayerPreviewPrusaDialectTest {

    private fun gcode(vararg lines: String): File {
        val file = File.createTempFile("prusa-preview", ".gcode")
        file.deleteOnExit()
        file.writeText(lines.joinToString("\n") + "\n")
        return file
    }

    @Test
    fun parsesPrusaLayerChangeMarkersIntoNumberedLayers() {
        val file = gcode(
            "; generated by PrusaSlicer 2.9.6",
            "G90",
            "M83",
            ";LAYER_CHANGE",
            ";Z:0.2",
            ";HEIGHT:0.2",
            "G1 X10 Y10 F1200",
            "G1 X20 Y10 E0.5",
            ";TYPE:External perimeter",
            "G1 X20 Y20 E0.5",
            ";LAYER_CHANGE",
            ";Z:0.4",
            ";HEIGHT:0.2",
            ";TYPE:Support material",
            "G1 X15 Y15 E0.4",
            ";LAYER_CHANGE",
            ";Z:0.6",
            ";HEIGHT:0.2",
            ";TYPE:Skirt/Brim",
            "G1 X5 Y5 E0.4",
        )

        val preview = GcodeLayerPreviewParser.parse(file, GcodeDialect.PRUSA)
        preview.layers.forEach { println("DBG L" + it.number + " src=" + it.sourceSegmentCount + " segs=" + it.segmentCount + " z=" + it.z + " sup=" + it.supportSegmentCount + " supI=" + it.supportInterfaceSegmentCount) }
        assertEquals(3, preview.layers.size)
        assertEquals(1, preview.layers[0].number)
        assertEquals(0.2f, preview.layers[0].z, 0.001f)
        assertEquals(0.4f, preview.layers[0].z + preview.layers[0].height, 0.001f)
        assertEquals(2, preview.layers[1].number)
        assertTrue("src=" + preview.layers[0].sourceSegmentCount + " segs=" + preview.layers[0].segmentCount, preview.layers[0].sourceSegmentCount >= 2)
        assertEquals("supportSegs=" + preview.layers[1].supportSegmentCount, 1, preview.layers[1].supportSegmentCount)
    }

    @Test
    fun mapsPrusaTypesToFeatures() {
        val file = gcode(
            "G90",
            "M83",
            ";LAYER_CHANGE",
            ";Z:0.2",
            "G1 X0 Y0 E0.1",
            ";TYPE:External perimeter",
            "G1 X10 Y0 E0.1",
            ";TYPE:Support material",
            "G1 X10 Y10 E0.1",
            ";TYPE:Support material interface",
            "G1 X20 Y10 E0.1",
            ";TYPE:Skirt/Brim",
            "G1 X20 Y0 E0.1",
            ";TYPE:Top surface",
            "G1 X0 Y0 E0.1",
        )

        val preview = GcodeLayerPreviewParser.parse(file, GcodeDialect.PRUSA)
        assertEquals(1, preview.layers.size)
        assertEquals(5, preview.layers[0].segmentCount)
    }

    @Test
    fun curaDialectIsUnchangedForPrusaStyleFiles() {
        // Cura dialect sees no ;LAYER:, so every move happens before the first layer marker.
        val file = gcode(
            ";LAYER_CHANGE",
            ";Z:0.2",
            "G1 X10 Y10 E0.5",
        )

        val curaPreview = runCatching { GcodeLayerPreviewParser.parse(file, GcodeDialect.CURA) }
        assertTrue(curaPreview.isFailure || curaPreview.getOrNull()?.layers.orEmpty().isEmpty())
    }

    @Test
    fun parseProgressRejectsNonPercentLines() {
        val runnerProgress = PrusaEngineRunner.progressFrom("10 => Processing triangulated mesh")
        assertEquals(10, runnerProgress)
        assertNull(PrusaEngineRunner.progressFrom("Slicing result exported..."))
    }
}
