package com.tomppi.enderslicer.engine

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * What the KAMP injector will and will not add to a start script.
 *
 * The script is the user's own text, which is the only part of a slice the app's GcodeSanitizer
 * trusts with a Klipper command: the first version of this wrote BED_MESH_CALIBRATE into the
 * sliced file instead, and every slice was rejected as malformed and withheld. These hold the
 * shape of the answer - a script in, a script out - as well as the four cases where it must add
 * nothing.
 */
class KlipperBedMeshInjectorTest {
    private val startScript = listOf(
        "; generated by a slicer",
        "M104 S200",
        "G28 ; home all axes",
        "G1 X5 Y5 Z0.3 F3000",
        ";LAYER:0",
        "G1 X20 Y20 E1.5 F1200",
        "G1 X40 Y20 E1.5 F1200",
        "",
    ).joinToString("\n")

    private fun lines(script: String) = script.lines()

    @Test
    fun theCallIsAddedInFrontOfTheFirstExtrudingMove() {
        val result = KlipperBedMeshInjector.withMeshCall(startScript)
        val out = lines(result)
        val marker = out.indexOf(KlipperBedMeshInjector.MARKER)
        assertTrue("the marker is missing", marker >= 0)
        assertEquals("BED_MESH_CALIBRATE", out[marker + 1])
        assertTrue("the call has to follow homing", marker > out.indexOf("G28 ; home all axes"))
        assertTrue("the call has to precede the extrusion", marker < out.indexOfFirst { it.startsWith("G1 X20 Y20 E") })
    }

    @Test
    fun theScriptItselfIsLeftAlone() {
        val result = KlipperBedMeshInjector.withMeshCall(startScript)
        assertEquals(startScript, result.replace(KlipperBedMeshInjector.MARKER + "\nBED_MESH_CALIBRATE\n", ""))
    }

    @Test
    fun aScriptThatMeasuresItsOwnMeshIsUntouched() {
        val withCall = startScript.replace("G28 ; home all axes", "G28 ; home all axes\nBED_MESH_CALIBRATE")
        assertEquals(withCall, KlipperBedMeshInjector.withMeshCall(withCall))
        val withG29 = startScript.replace("G28 ; home all axes", "G28 ; home all axes\nG29")
        assertEquals(withG29, KlipperBedMeshInjector.withMeshCall(withG29))
    }

    @Test
    fun aScriptThatNeverHomesIsUntouched() {
        val noHoming = "; nothing homed here\nG1 X20 Y20 E1.5 F1200\n"
        assertEquals(noHoming, KlipperBedMeshInjector.withMeshCall(noHoming))
    }

    @Test
    fun aScriptWithNothingToPrintIsUntouched() {
        val travelOnly = "G28\nG1 X10 Y10 F3000\n"
        assertEquals(travelOnly, KlipperBedMeshInjector.withMeshCall(travelOnly))
    }

    @Test
    fun aSecondPassAddsNothing() {
        val once = KlipperBedMeshInjector.withMeshCall(startScript)
        assertEquals(once, KlipperBedMeshInjector.withMeshCall(once))
        assertEquals(1, lines(once).count { it == KlipperBedMeshInjector.MARKER })
    }

    @Test
    fun aScriptWithCrlfEndingsIsStillUnderstood() {
        // A profile imported from a Windows editor, or one of the Creality start scripts, ends
        // its lines with CRLF. The parser reads a trailing carriage return as part of the last
        // parameter, so the extruding move went unrecognised and nothing was added in front of
        // it - the call was silently missing on the printer this was built for.
        val crlf = startScript.replace("\n", "\r\n")
        val result = KlipperBedMeshInjector.withMeshCall(crlf)
        val out = result.lines()
        val marker = out.indexOf(KlipperBedMeshInjector.MARKER)
        assertTrue("the marker is missing", marker >= 0)
        assertEquals("BED_MESH_CALIBRATE", out[marker + 1])
        assertTrue(
            "the call has to precede the extrusion",
            marker < out.indexOfFirst { it.startsWith("G1 X20 Y20 E") },
        )
        assertFalse("a carriage return survived into the output", result.contains("\r"))
    }

    @Test
    fun theSwitchAndTheRouteBothHaveToAgree() {
        assertEquals(
            startScript,
            KlipperBedMeshInjector.withMeshCallIfWanted(enabled = false, flavor = "Klipper", startGcode = startScript),
        )
        assertEquals(
            startScript,
            KlipperBedMeshInjector.withMeshCallIfWanted(enabled = true, flavor = "Marlin", startGcode = startScript),
        )
        assertFalse(
            KlipperBedMeshInjector.withMeshCallIfWanted(enabled = true, flavor = "Klipper", startGcode = startScript) == startScript,
        )
    }
}
