package com.tomppi.enderslicer.engine

import java.io.File
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The Klipper side of adaptive meshing: what this injector will and will not write.
 *
 * KAMP only meshes adaptively when a file asks for a mesh after declaring its objects, so the
 * injector's whole job is to notice whether the start script already measures one. These hold
 * it to that, including the two cases where writing a line would be worse than writing none:
 * a printer that was never homed, and a file that has already been through here.
 */
class KlipperBedMeshInjectorTest {
    private fun gcode(text: String): File {
        val file = File.createTempFile("kamp-injector", ".gcode")
        file.deleteOnExit()
        file.writeText(text)
        return file
    }

    /** A start script of the shape the engines emit: home, travel, then the first layer. */
    private val startScript = """
        ; generated by a slicer
        M104 S200
        G28 ; home all axes
        G1 X5 Y5 Z0.3 F3000
        ;LAYER:0
        G1 X20 Y20 E1.5 F1200
        G1 X40 Y20 E1.5 F1200
    """.trimIndent() + "\n"

    @Test
    fun insertsTheMeshCallBeforeTheFirstExtrudingMove() {
        val file = gcode(startScript)
        assertTrue(KlipperBedMeshInjector.inject(file))
        val lines = file.readText().lines()
        val marker = lines.indexOf(KlipperBedMeshInjector.MARKER)
        assertTrue("the marker is missing", marker >= 0)
        assertEquals("BED_MESH_CALIBRATE", lines[marker + 1])
        assertTrue("the call has to follow homing", marker > lines.indexOf("G28 ; home all axes"))
        assertTrue(
            "the call has to precede the extrusion",
            marker < lines.indexOfFirst { it.startsWith("G1 X20 Y20 E") },
        )
    }

    @Test
    fun leavesAFileThatMeasuresItsOwnMeshAlone() {
        val file = gcode(startScript.replace("G28 ; home all axes", "G28 ; home all axes\nBED_MESH_CALIBRATE"))
        val before = file.readText()
        assertFalse(KlipperBedMeshInjector.inject(file))
        assertEquals(before, file.readText())
    }

    @Test
    fun leavesAFileThatProbesWithG29Alone() {
        val file = gcode(startScript.replace("G28 ; home all axes", "G28 ; home all axes\nG29"))
        val before = file.readText()
        assertFalse(KlipperBedMeshInjector.inject(file))
        assertEquals(before, file.readText())
    }

    @Test
    fun writesNothingWhenThePrinterWasNeverHomed() {
        val file = gcode("; no homing in this script\nG1 X20 Y20 E1.5 F1200\n")
        val before = file.readText()
        assertFalse(KlipperBedMeshInjector.inject(file))
        assertEquals(before, file.readText())
    }

    @Test
    fun writesNothingWhenThereIsNoExtrusionAtAll() {
        val file = gcode("G28\nG1 X10 Y10 F3000\n")
        assertFalse(KlipperBedMeshInjector.inject(file))
    }

    @Test
    fun aSecondRunChangesNothing() {
        val file = gcode(startScript)
        assertTrue(KlipperBedMeshInjector.inject(file))
        val once = file.readText()
        assertFalse(KlipperBedMeshInjector.inject(file))
        assertEquals(once, file.readText())
        assertEquals(1, once.lines().count { it == KlipperBedMeshInjector.MARKER })
    }
}
