package com.tomppi.enderslicer.engine

import android.content.Context
import android.content.res.AssetManager
import com.tomppi.enderslicer.model.PrinterDefinition
import com.tomppi.enderslicer.model.PrusaPresetCatalog
import com.tomppi.enderslicer.model.PrusaPresetRepository
import com.tomppi.enderslicer.model.PrusaPresetRepository.Companion.ReadResult
import com.tomppi.enderslicer.model.PrusaPresetSelection
import com.tomppi.enderslicer.model.PrusaSliceSettings
import com.tomppi.enderslicer.model.SlicerSettings
import com.tomppi.enderslicer.model.withSettings
import java.io.File
import java.time.Instant
import java.util.UUID
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runInterruptible

/**
 * Runs the bundled PrusaSlicer 3.0.0-alpha11 console for Android.
 *
 * The console is packaged as a native library ("libprusa_slicer_exec.so" in the
 * APK's arm64-v8a jniLibs, executed directly). It consumes a self-contained
 * JSON configuration generated by [PrusaConfigWriter] (--load format) plus the bundled resources directory
 * (passed via --datadir), and emits PrusaSlicer-dialect G-code.
 */
class PrusaEngineRunner(private val context: Context) {

    data class SliceResult(
        val artifactId: String,
        val gcodeFile: File,
        val baseGcodeFile: File,
        val logFile: File,
        val elapsedMilliseconds: Long,
        val estimatedPrintSeconds: Int?,
        val layerPreview: GcodeLayerPreview?,
        val layerEvents: List<LayerEvent>,
    )

    class SliceException(
        message: String,
        val logFile: File,
        cause: Throwable? = null,
    ) : Exception(message, cause)

    private data class Workspace(
        val id: String,
        val directory: File,
        val output: File = File(directory, "output.gcode"),
        val model: File = File(directory, "model.stl"),
        val config: File = File(directory, "prusa-config.json"),
    )

    private val nativeDirectory = File(context.applicationInfo.nativeLibraryDir)
    private val executable = File(nativeDirectory, ENGINE_LIBRARY_NAME)
    private val publisher = SliceArtifactPublisher(File(context.filesDir, SliceArtifactPublisher.RESULTS_DIRECTORY_NAME))
        private val baseConfigJson: String by lazy {
        context.assets.open("prusa3-base.json").use { input ->
            input.readBytes().toString(Charsets.UTF_8)
        }
    }

private val datadir = File(context.filesDir, "prusa/datadir")

    fun isAvailable(): Boolean = executable.isFile && executable.length() > 0L

    fun status(): String = when {
        !executable.exists() -> "PrusaSlicer 3.0.0-alpha11 is not packaged in this APK"
        !executable.isFile -> "PrusaSlicer package path is invalid"
        executable.length() == 0L -> "PrusaSlicer package is empty"
        else -> "PrusaSlicer 3.0.0-alpha11 ready"
    }

    fun releaseArtifact(id: String) = publisher.release(id)

    /**
     * Extracts the bundled PrusaSlicer resources next to the config dir on first
     * use. Returns true when the resources are present and complete.
     */
    fun baseConfig(): String = baseConfigJson

    /**
     * The chosen presets as typed configuration values, or null when the picker was never used.
     *
     * The repository JSON is 2 MB, so it is read once per process, on the slicing thread.
     * Every reason a selection cannot be layered is appended to [log] - an unusable catalogue,
     * a stored machine or profile the bundle no longer offers - because the base configuration
     * it falls back to is otherwise indistinguishable from the user never having picked one.
     */
    private fun presetBuckets(selection: PrusaPresetSelection, log: File): PrusaPresetValues.Buckets? {
        if (!selection.isActive) return null
        val catalog = when (val result = presetCatalogResult) {
            is ReadResult.Loaded -> presetCatalog
            ReadResult.Absent -> {
                appendLog(log, "\nPrusaSlicer presets: " + PrusaPresetRepository.ASSET + " is not packaged in this APK; slicing with the base configuration\n")
                null
            }
            ReadResult.Empty -> {
                appendLog(log, "\nPrusaSlicer presets: " + PrusaPresetRepository.ASSET + " carries no presets; slicing with the base configuration\n")
                null
            }
            is ReadResult.Unreadable -> {
                appendLog(log, "\nPrusaSlicer presets: " + PrusaPresetRepository.ASSET + " could not be read (" + result.reason + "); slicing with the base configuration\n")
                null
            }
        } ?: return null
        catalog.unavailableReason?.let { reason ->
            appendLog(log, "\nPrusaSlicer presets: " + reason + "; slicing with the base configuration\n")
            return null
        }
        val printerId = selection.printerId
        val printer = printerId?.let(catalog::printer)
        if (printer == null) {
            appendLog(log, "\nPrusaSlicer presets: the stored machine '" + printerId + "' is no longer in the bundle; slicing with the base configuration\n")
            return null
        }
        if (selection.printName != null && !catalog.hasPrint(printer, selection.printName)) {
            appendLog(log, "\nPrusaSlicer presets: the stored print profile '" + selection.printName + "' is no longer offered for " + printer.label + "; slicing without it\n")
        }
        if (selection.filamentName != null && !catalog.hasFilament(printer, selection.filamentName)) {
            appendLog(log, "\nPrusaSlicer presets: the stored filament profile '" + selection.filamentName + "' is no longer offered for " + printer.label + "; slicing without it\n")
        }
        val print = selection.printName ?: catalog.defaultPrint(printer)
        val filament = selection.filamentName ?: catalog.defaultFilament(printer)
        return PrusaPresetValues.map(
            baseConfigJson = baseConfigJson,
            printerValues = catalog.resolvePrinter(printer),
            printValues = print?.let { catalog.resolvePrint(printer, it) }.orEmpty(),
            filamentValues = filament?.let { catalog.resolveFilament(printer, it) }.orEmpty(),
        )
    }

    private val presetCatalogResult: ReadResult by lazy {
        PrusaPresetRepository.readResult(context.assets)
    }

    private val presetCatalog: PrusaPresetCatalog? by lazy {
        (presetCatalogResult as? ReadResult.Loaded)?.repository?.let(::PrusaPresetCatalog)
    }

    fun prepareResources(): Boolean {
        // 3.x console layout: --datadir <dir> reads <dir>/presets (plus cache).
        val marker = File(datadir, ".resources-version")
        if (marker.isFile && marker.readText().trim() == RESOURCES_VERSION) {
            return File(datadir, "presets").isDirectory
        }
        val presets = File(datadir, "presets")
        if (presets.exists()) presets.deleteRecursively()
        presets.mkdirs()
        copyAssetDir(context.assets, "prusa/resources/presets", presets)
        File(datadir, "cache").mkdirs()
        marker.writeText(RESOURCES_VERSION)
        return File(datadir, "presets/prusa-research-fff").isDirectory
    }

    suspend fun slice(
        modelFile: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        machineSettings: SlicerSettings,
        startGcode: String,
        endGcode: String,
        presets: PrusaPresetSelection = PrusaPresetSelection.NONE,
        onProgress: (Int) -> Unit = {},
    ): SliceResult = runInterruptible(Dispatchers.IO) {
        sliceBlocking(
            modelFile, printer, settings, machineSettings, startGcode, endGcode, presets, onProgress,
        )
    }

    private fun sliceBlocking(
        modelFile: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        machineSettings: SlicerSettings,
        startGcode: String,
        endGcode: String,
        presets: PrusaPresetSelection,
        onProgress: (Int) -> Unit,
    ): SliceResult {
        require(isAvailable()) { status() }
        require(modelFile.isFile && modelFile.length() > 0L) { "The imported STL is no longer available" }
        if (!prepareResources()) {
            throw IllegalStateException("PrusaSlicer resources are not packaged in this APK")
        }

        val workspace = createWorkspace()
        val log = requestLog(workspace.id)
        val started = System.nanoTime()
        val effectivePrinter = effectiveMachine(printer, machineSettings)
        val printerEnvelope = PrinterEnvelope.from(printer.withSettings(machineSettings))

        try {
            writeInitialLog(log, workspace.id, modelFile, printer, settings, startGcode, endGcode, datadir)

            modelFile.copyTo(workspace.model, overwrite = false)
            val presetBuckets = presetBuckets(presets, log)
            presetBuckets?.let { applied ->
                appendLog(
                    log,
                    "\nPrusaSlicer presets: printer=" + presets.printerId +
                        " print=" + (presets.printName ?: "default") +
                        " filament=" + (presets.filamentName ?: "default") +
                        " (" + applied.printer.length() + " printer, " + applied.print.length() +
                        " print, " + applied.filament.length() + " filament values, " +
                        applied.skipped.size + " skipped)\n",
                )
            }
            val config = PrusaConfigWriter.write(
                workspace.config, settings, effectivePrinter, startGcode, endGcode, baseConfig(),
                presets = presetBuckets,
            )

            val command = listOf(
                executable.absolutePath,
                "--datadir", datadir.absolutePath,
                "--load", config.absolutePath,
                "--export-gcode",
                "-o", workspace.output.absolutePath,
                workspace.model.absolutePath,
            )
            appendLog(log, "\nPrusaSlicer command:\n" + command.joinToString(" ") + "\n")

            val processBuilder = ProcessBuilder(command)
                .directory(workspace.directory)
                .redirectErrorStream(true)
                .apply {
                    environment()["LD_LIBRARY_PATH"] = nativeDirectory.absolutePath
                    environment()["TMPDIR"] = workspace.directory.absolutePath
                    environment()["HOME"] = context.filesDir.absolutePath
                }

            val exitCode = runWithProgress(processBuilder::start, log, onProgress)

            if (exitCode != 0) {
                throw SliceException(
                    "PrusaSlicer failed with exit code $exitCode. Export the error log for full details.",
                    log,
                )
            }
            validateOutput(workspace.output, log)
            throwIfInterrupted()

            val transport = "prusa-json"
            val summary = GcodeSanitizer.validateAndRepair(
                file = workspace.output,
                settingsTransport = transport,
                printerEnvelope = printerEnvelope,
                dialect = GcodeDialect.PRUSA,
                userGcode = listOf(startGcode, endGcode),
            )
            if (machineSettings.adaptiveMeshLevelingEnabled) {
                AdaptiveBedMeshInjector.inject(workspace.output, printerEnvelope, machineSettings.amlMarginMm, machineSettings.amlGridPoints)
            }
            val prusaEstimateSeconds = parsePrusaEstimateSeconds(workspace.output) ?: summary.estimatedSeconds
            val preview = runCatching {
                GcodeLayerPreviewParser.parse(workspace.output, GcodeDialect.PRUSA)
            }.getOrNull()

            val artifact = publisher.publish(
                id = workspace.id,
                gcodeSource = workspace.output,
                baseGcodeSource = workspace.output,
                printerEnvelope = printerEnvelope,
            )
            val elapsed = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - started)
            appendResultLog(log, artifact, summary, preview, elapsed)
            updateLatestLog(log)
            return SliceResult(
                artifactId = artifact.id,
                gcodeFile = artifact.gcodeFile,
                baseGcodeFile = artifact.baseGcodeFile,
                logFile = log,
                elapsedMilliseconds = elapsed,
                estimatedPrintSeconds = prusaEstimateSeconds,
                layerPreview = preview,
                layerEvents = emptyList(),
            )
        } catch (error: InterruptedException) {
            appendLog(log, "\n--- TrioSlicer cancellation ---\nFinished: " + Instant.now() + "\nThe PrusaSlicer request was cancelled and reaped.\n")
            updateLatestLog(log)
            throw error
        } catch (error: Throwable) {
            appendLog(log, "\n--- TrioSlicer failure ---\nFinished: " + Instant.now() + "\n" + error.stackTraceToString() + "\n")
            updateLatestLog(log)
            if (error is SliceException) throw error
            throw SliceException(error.message ?: "PrusaSlicer failed before slicing started", log, error)
        } finally {
            workspace.directory.deleteRecursively()
        }
    }

    /**
     * Parses "; estimated printing time (normal mode) = 22m 46s" (or "4h 10m 3s").
     *
     * The fields are clamped rather than parsed as Int directly: the comment is
     * read after PrusaSlicer has already succeeded, so an absurd digit run must
     * not turn a finished slice into a NumberFormatException.
     */
    private fun parsePrusaEstimateSeconds(file: File): Int? {
        file.bufferedReader().useLines { lines ->
            for (line in lines) {
                if (!line.startsWith("; estimated printing time")) continue
                return parseEnginePrintTimeEstimate(line.substringAfter('=').trim())
            }
        }
        return null
    }

    private fun validateOutput(file: File, log: File) {
        if (!file.isFile || file.length() < MINIMUM_GCODE_BYTES) {
            throw SliceException("PrusaSlicer finished without producing a valid G-code file. Export the error log for details.", log)
        }
        val header = file.bufferedReader().use { reader ->
            buildString {
                repeat(20) {
                    val line = reader.readLine() ?: return@repeat
                    appendLine(line)
                }
            }
        }
        if (header.isBlank() || !header.contains("PrusaSlicer")) {
            throw SliceException("The engine output did not contain a PrusaSlicer G-code header. Export the error log for details.", log)
        }
    }

    /** Overlays the user-edited machine values (same ones the Cura path honors). */
    private fun effectiveMachine(printer: PrinterDefinition, settings: SlicerSettings): PrinterDefinition =
        printer.copy(
            widthMm = settings.machineWidthMm,
            depthMm = settings.machineDepthMm,
            heightMm = settings.machineHeightMm,
            originAtCenter = settings.originAtCenter,
            heatedBed = settings.heatedBed,
            gcodeFlavor = settings.gcodeFlavor,
            nozzleSizeMm = settings.nozzleSizeMm,
            filamentDiameterMm = settings.filamentDiameterMm,
            extruders = settings.enabledExtruderCount,
        )

    private fun createWorkspace(): Workspace {
        val id = "prusa-${System.currentTimeMillis()}-${UUID.randomUUID()}"
        val root = File(context.cacheDir, "prusaengine/requests").apply {
            check(mkdirs() || isDirectory) { "Unable to create the PrusaSlicer request directory" }
        }
        val cutoff = System.currentTimeMillis() - STALE_WORKSPACE_AGE_MILLIS
        root.listFiles().orEmpty()
            .filter { it.isDirectory && it.lastModified() in 1 until cutoff }
            .forEach(File::deleteRecursively)
        cleanupStaleRequestLogs(File(context.filesDir, "logs"), "prusaengine-")
        val directory = File(root, id)
        check(directory.mkdir()) { "Unable to create an isolated PrusaSlicer workspace" }
        return Workspace(id, directory)
    }

    private fun requestLog(id: String): File = File(context.filesDir, "logs/prusaengine-$id.log").apply {
        parentFile?.mkdirs()
    }

    private fun writeInitialLog(
        log: File,
        id: String,
        model: File,
        printer: PrinterDefinition,
        settings: PrusaSliceSettings,
        startGcode: String,
        endGcode: String,
        datadir: File,
    ) {
        log.writeText(
            buildString {
                appendLine("TrioSlicer PrusaSlicer diagnostic log")
                appendLine("Executable: " + executable.absolutePath)
                appendLine("Datadir: " + datadir.absolutePath)
                appendLine("Model: " + model.absolutePath)
                appendLine("Printer: " + printer.name + " (" + printer.widthMm + "x" + printer.depthMm + "mm, nozzle " + printer.nozzleSizeMm + "mm)")
                appendLine("Layer height: " + settings.layerHeightMm + "mm")
                appendLine("Perimeters: " + settings.perimeters + " · Fill: " + settings.fillDensityPercent + "% " + settings.fillPattern)
                appendLine("Start G-code (" + startGcode.length + " bytes)")
                appendLine("End G-code (" + endGcode.length + " bytes)")
                appendLine("Started: " + Instant.now())
            },
        )
    }

    private fun appendResultLog(
        log: File,
        artifact: SliceArtifactPublisher.PublishedArtifact,
        summary: GcodeSanitizer.Summary,
        preview: GcodeLayerPreview?,
        elapsedMillis: Long,
    ) {
        appendLog(
            log,
            buildString {
                appendLine("\n--- PrusaSlicer result ---")
                appendLine("Artifact: " + artifact.id)
                appendLine("G-code: " + artifact.gcodeFile.absolutePath + " (" + artifact.gcodeFile.length() + " bytes)")
                appendLine("Estimated print time (s): " + summary.estimatedSeconds)
                appendLine("Layer preview: " + if (preview != null) preview.layers.size.toString() + " layers" else "unavailable")
                appendLine("Elapsed: " + elapsedMillis + "ms")
            },
        )
    }

    private fun appendLog(log: File, text: String) {
        runCatching { log.appendText(text) }
    }

    private fun updateLatestLog(log: File) = updateLatestLog(log, "latest-prusaengine.log")

    private fun throwIfInterrupted() {
        if (Thread.currentThread().isInterrupted) throw InterruptedException("PrusaSlicer slicing was cancelled")
    }

    private fun copyAssetDir(assets: AssetManager, from: String, destination: File) {
        AssetTreeExtractor.copyTree(assets, from, destination)
    }

    companion object {
        /**
         * Starts the process, streams merged output into [log] while parsing
         * PrusaSlicer progress lines ("NN => stage") into [onProgress], and applies
         * the same timeout and kill semantics as the other engines.
         *
         * The loop itself is [OwnedProcessRunner.runStreaming];
         * [PrusaProcessOwnershipTest] drives the child's ownership through this.
         */
        internal fun runWithProgress(
            start: () -> Process,
            log: File,
            onProgress: (Int) -> Unit,
        ): Int = OwnedProcessRunner.runStreaming(
            start = start,
            log = log,
            // The request header is already in this file, so the stream appends:
            // opening it fresh truncated the header - request id, model, printer and
            // the resolved settings - leaving only the engine's own output.
            appendToLog = true,
            parseProgress = { line -> progressFrom(line) },
            onProgress = onProgress,
            timeout = SLICE_TIMEOUT_MINUTES,
            unit = TimeUnit.MINUTES,
        ) ?: throw SliceException(
            "PrusaSlicer timed out after $SLICE_TIMEOUT_MINUTES minutes. Export the error log for details.",
            log,
        )

        /** Accepts "10 => Processing triangulated mesh" style lines. */
        internal fun progressFrom(line: String): Int? {
            val trimmed = line.trimStart()
            val marker = trimmed.indexOf("=>")
            if (marker <= 0) return null
            return trimmed.substring(0, marker).trim().toIntOrNull()
        }

        const val ENGINE_LIBRARY_NAME = "libprusa_slicer_exec.so"
        private const val RESOURCES_VERSION = "prusaslicer-3.0.0-alpha11-resources-v1"
        private const val SLICE_TIMEOUT_MINUTES = 60L
        private const val STALE_WORKSPACE_AGE_MILLIS = 24L * 60 * 60 * 1000
        private const val MINIMUM_GCODE_BYTES = 256L
    }
}
