#!/usr/bin/env python3
"""Generate the TrioSlicer launcher icon from one geometry definition.

Three extruder hotends - CuraEngine blue, PrusaSlicer orange, OrcaSlicer teal - drawn as
polygons and emitted three ways:

  docs/trioslicer-icon.svg                                  the artwork of record
  app/src/main/res/drawable/trioslicer_icon_foreground.xml   adaptive icon foreground
  app/src/main/res/mipmap-anydpi/ic_launcher.xml             pre-26 launcher icon (with plate)
  app/src/main/res/values/icon_colors.xml                    the adaptive background colour

Every shape stays inside the 66 dp adaptive-icon safe zone of the 108 dp viewport, and the
same polygons are rasterised (4x supersampled) into a preview PNG so the result can be looked
at without a vector renderer:

  python3 scripts/generate-app-icon.py build/trioslicer-icon-preview.png
"""
import os
import struct
import sys
import zlib

VIEWPORT = 108.0
BACKGROUND = (0x10, 0x15, 0x1C)

# The app's own accents, dark variants.
BLUE = (0x4C, 0xA2, 0xFF)
ORANGE = (0xFF, 0x9E, 0x45)
TEAL = (0x4D, 0xB6, 0xAC)

WIDTH = 15.0
SPACING = 4.0
LEFT = 26.5
TOP = 32.0


def shade(colour, factor):
    return tuple(max(0, min(255, int(round(channel * factor)))) for channel in colour)


def hotend(x0, colour):
    """One hotend: filament, finned heatsink, heater block, nozzle cone and tip."""
    dark = shade(colour, 0.72)
    x1 = x0 + WIDTH
    block = 1.0
    return [
        # filament entering the heatsink, translucent
        (colour, 0.55, [(x0 + 5.5, TOP), (x0 + 9.5, TOP), (x0 + 9.5, TOP + 4.0), (x0 + 5.5, TOP + 4.0)]),
        # heatsink
        (colour, 1.0, [(x0, TOP + 4.0), (x1, TOP + 4.0), (x1, TOP + 16.0), (x0, TOP + 16.0)]),
        # two fin slots cut out of the heatsink
        (BACKGROUND, 1.0, [(x0 + 1.5, TOP + 7.0), (x1 - 1.5, TOP + 7.0), (x1 - 1.5, TOP + 8.5), (x0 + 1.5, TOP + 8.5)]),
        (BACKGROUND, 1.0, [(x0 + 1.5, TOP + 11.0), (x1 - 1.5, TOP + 11.0), (x1 - 1.5, TOP + 12.5), (x0 + 1.5, TOP + 12.5)]),
        # heater block, a little wider than the heatsink
        (colour, 1.0, [(x0 - block, TOP + 16.0), (x1 + block, TOP + 16.0), (x1 + block, TOP + 25.0), (x0 - block, TOP + 25.0)]),
        # nozzle cone, darker so the block reads as a separate part
        (dark, 1.0, [
            (x0 - block, TOP + 25.0), (x1 + block, TOP + 25.0),
            (x0 + 8.7, TOP + 38.0), (x0 + 6.3, TOP + 38.0),
        ]),
        # nozzle tip
        (dark, 1.0, [(x0 + 6.3, TOP + 38.0), (x0 + 8.7, TOP + 38.0), (x0 + 8.7, TOP + 43.0), (x0 + 6.3, TOP + 43.0)]),
    ]


def shapes():
    result = []
    for index, colour in enumerate((BLUE, ORANGE, TEAL)):
        result.extend(hotend(LEFT + index * (WIDTH + SPACING), colour))
    return result


def hex_colour(colour, alpha=None):
    if alpha is None:
        return "#%02X%02X%02X" % colour
    return "#%02X%02X%02X%02X" % ((alpha,) + colour)


def svg_path(points):
    head = "M%g,%g" % points[0]
    rest = "".join("L%g,%g" % point for point in points[1:])
    return head + rest + "Z"


def write_svg(path):
    scale = 512.0 / VIEWPORT
    lines = [
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" role="img" aria-labelledby="title description">',
        '  <title id="title">TrioSlicer icon</title>',
        '  <desc id="description">Rounded dark app icon with three extruder hotends: blue (CuraEngine), orange (PrusaSlicer) and teal (OrcaSlicer).</desc>',
        '  <rect width="512" height="512" rx="112" fill="' + hex_colour(BACKGROUND) + '"/>',
        '  <g transform="scale(%g)">' % scale,
    ]
    for colour, opacity, points in shapes():
        attributes = ' fill="' + hex_colour(colour) + '"'
        if opacity < 1.0:
            attributes += ' fill-opacity="%g"' % opacity
        lines.append('    <path' + attributes + ' d="' + svg_path(points) + '"/>')
    lines.append('  </g>')
    lines.append('</svg>')
    write(path, "\n".join(lines) + "\n")


def write_foreground(path):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/generate-app-icon.py: TrioSlicer - three extruder hotends,',
        '     CuraEngine blue, PrusaSlicer orange and OrcaSlicer teal. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
    ]
    for colour, opacity, points in shapes():
        alpha = None if opacity >= 1.0 else int(round(opacity * 255))
        lines.append(
            '    <path android:fillColor="' + hex_colour(colour, alpha) +
            '" android:pathData="' + svg_path(points) + '" />',
        )
    lines.append('</vector>')
    write(path, "\n".join(lines) + "\n")


def write_legacy(path):
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        '<!-- Generated by scripts/generate-app-icon.py: the pre-26 launcher icon, plate included. -->',
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    android:width="108dp"',
        '    android:height="108dp"',
        '    android:viewportWidth="108"',
        '    android:viewportHeight="108">',
        '    <path android:fillColor="' + hex_colour(BACKGROUND) + '" android:pathData="M0,0H108V108H0Z" />',
    ]
    for colour, opacity, points in shapes():
        alpha = None if opacity >= 1.0 else int(round(opacity * 255))
        lines.append(
            '    <path android:fillColor="' + hex_colour(colour, alpha) +
            '" android:pathData="' + svg_path(points) + '" />',
        )
    lines.append('</vector>')
    write(path, "\n".join(lines) + "\n")


def write_adaptive(path):
    write(
        path,
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<!-- Generated by scripts/generate-app-icon.py. -->\n'
        '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
        '    <background android:drawable="@color/trioslicer_icon_background" />\n'
        '    <foreground android:drawable="@drawable/trioslicer_icon_foreground" />\n'
        '</adaptive-icon>\n',
    )


def write_colors(path):
    write(
        path,
        '<?xml version="1.0" encoding="utf-8"?>\n'
        '<resources>\n'
        '    <!-- Adaptive icon background: the same near-black plate the icon art sits on. -->\n'
        '    <color name="trioslicer_icon_background">' + hex_colour(BACKGROUND) + '</color>\n'
        '</resources>\n',
    )


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(text)
    print("wrote " + path)


# --- preview ----------------------------------------------------------------------------


def rasterise(size, supersample=4):
    """Fills the polygons into an RGBA buffer; only what the icon needs."""
    scale = size * supersample / VIEWPORT
    width = height = size * supersample
    pixels = [[(0, 0, 0, 0)] * width for _ in range(height)]
    for colour, opacity, points in shapes():
        alpha = opacity
        scaled = [(x * scale, y * scale) for x, y in points]
        for y in range(height):
            centre = y + 0.5
            crossings = []
            for index in range(len(scaled)):
                x1, y1 = scaled[index]
                x2, y2 = scaled[(index + 1) % len(scaled)]
                if (y1 <= centre < y2) or (y2 <= centre < y1):
                    crossings.append(x1 + (centre - y1) * (x2 - x1) / (y2 - y1))
            crossings.sort()
            for index in range(0, len(crossings) - 1, 2):
                start = max(0, int(crossings[index] + 0.5))
                end = min(width, int(crossings[index + 1] + 0.5))
                for x in range(start, end):
                    base = pixels[y][x]
                    pixels[y][x] = tuple(
                        int(round(colour[channel] * alpha + base[channel] * (1 - alpha)))
                        for channel in range(3)
                    ) + (max(base[3], int(round(255 * alpha))),)
    # downsample, and composite over the rounded plate
    result = []
    for y in range(size):
        row = []
        for x in range(size):
            totals = [0, 0, 0, 0]
            for dy in range(supersample):
                for dx in range(supersample):
                    pixel = pixels[y * supersample + dy][x * supersample + dx]
                    for channel in range(4):
                        totals[channel] += pixel[channel]
            row.append(tuple(total // (supersample * supersample) for total in totals))
        result.append(row)
    radius = size * 112.0 / 512.0
    for y in range(size):
        for x in range(size):
            if not inside_rounded(x + 0.5, y + 0.5, size, radius):
                result[y][x] = (0, 0, 0, 0)
                continue
            r, g, b, a = result[y][x]
            alpha = a / 255.0
            result[y][x] = tuple(
                int(round(channel * alpha + plate * (1 - alpha)))
                for channel, plate in zip((r, g, b), BACKGROUND)
            ) + (255,)
    return result


def inside_rounded(x, y, size, radius):
    cx = min(max(x, radius), size - radius)
    cy = min(max(y, radius), size - radius)
    return (x - cx) ** 2 + (y - cy) ** 2 <= radius ** 2


def write_png(path, size=512):
    pixels = rasterise(size)
    raw = b"".join(
        b"\x00" + b"".join(struct.pack("4B", *pixel) for pixel in row) for row in pixels
    )
    def chunk(tag, data):
        body = tag + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    png = b"\x89PNG\r\n\x1a\n"
    png += chunk(b"IHDR", struct.pack(">IIBBBBB", size, size, 8, 6, 0, 0, 0))
    png += chunk(b"IDAT", zlib.compress(raw, 9))
    png += chunk(b"IEND", b"")
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "wb") as handle:
        handle.write(png)
    print("wrote " + path)


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    write_svg(os.path.join(root, "docs/trioslicer-icon.svg"))
    write_foreground(os.path.join(root, "app/src/main/res/drawable/trioslicer_icon_foreground.xml"))
    write_legacy(os.path.join(root, "app/src/main/res/mipmap-anydpi/ic_launcher.xml"))
    write_adaptive(os.path.join(root, "app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml"))
    write_colors(os.path.join(root, "app/src/main/res/values/icon_colors.xml"))
    preview = sys.argv[1] if len(sys.argv) > 1 else os.path.join(root, "build/trioslicer-icon-preview.png")
    write_png(preview)


if __name__ == "__main__":
    main()
