#!/usr/bin/env bash
# Stage the OrcaSlicer resources the headless console reads at runtime into the app assets.
#
# Only the runtime directories ship. Everything else under resources/ belongs to the GUI:
# images/ (35M), fonts/ (35M), hms/ (63M), web/ (22M), shaders/, i18n/, dailytip/,
# handy_models/, cert/, tooltip/ - none of it is read by a libs3r-only console.
#
# The settings catalogue (assets/orca/all-settings.json) is generated by the engine itself:
#   printf '' | orca-console --datadir <staged resources> --dump-settings > all-settings.json
# It is committed because it is small and is the only record of the option names this engine
# build accepts; regenerate it whenever the engine version changes.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
SRC="${ORCA_SRC:-$REPO/.build/orca-src}"
DEST="$REPO/app/src/main/assets/orca/resources"

SHIP=(profiles info flush printers)
for d in "${SHIP[@]}"; do
  [ -d "$SRC/resources/$d" ] || { echo "FATAL: $SRC/resources/$d is missing" >&2; exit 1; }
done

rm -rf "$DEST"
mkdir -p "$DEST"
for d in "${SHIP[@]}"; do
  cp -r "$SRC/resources/$d" "$DEST/"
done

{
  echo "orcaslicer ${ORCA_TAG:-v2.4.2}"
  echo "resources: ${SHIP[*]}"
  git -C "$SRC" rev-parse HEAD 2>/dev/null || true
} > "$DEST/.source-version"

echo "staged $(du -sh "$DEST" | cut -f1) in $(find "$DEST" -type f | wc -l) files -> $DEST"
